const http=require('node:http'),crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path');
const {loadConfig}=require('./config.cjs');
const config=loadConfig();const CLIENT=config.clientId,BASE='http://127.0.0.1:'+config.port,REDIRECT=BASE+'/callback',KEY=crypto.randomBytes(24).toString('hex');
const ids={main:config.mainId,...Object.fromEntries(config.sourceIds.map((id,i)=>['source'+(i+1),id]))};
const labels=Object.fromEntries(Object.keys(ids).map(r=>[r,r==='main'?'MAIN — hedef hesap':'Kaynak hesap '+r.slice(6)]));
const DATA=path.resolve(__dirname,'../data');fs.mkdirSync(DATA,{recursive:true});let visibilityAccepted=false;
const {validateMutation,retryDelay}=require('./policy.cjs');
const pending=new Map(),accounts=new Map(),snapshots=new Map();let busy=false,queue=Promise.resolve(),nextRequest=0;const status={phase:'login',message:'Aktarım için hesap bağlantılarını tamamla.',accounts:{}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function write(file,data){const f=path.join(DATA,file);fs.writeFileSync(f+'.tmp',JSON.stringify(data,null,2));fs.renameSync(f+'.tmp',f);if(file==='transfer-report.json'){let out=path.join(DATA,'reports');fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'lilt-transfer-report.json'),JSON.stringify(data,null,2));}}
function read(file){try{return JSON.parse(fs.readFileSync(path.join(DATA,file),'utf8'));}catch(e){if(e.code==='ENOENT')return null;throw e;}}
function setStatus(message){status.message=message;write('migration-status.json',status);}
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function token(role){const a=accounts.get(role);if(!a)throw Error('Hesap bağlı değil: '+labels[role]);if(Date.now()>a.expires-60000){const r=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',refresh_token:a.refresh,client_id:CLIENT}),signal:AbortSignal.timeout(25000)});if(!r.ok)throw Error('Giriş yenilenemedi: '+labels[role]);const t=await r.json();a.token=t.access_token;a.refresh=t.refresh_token||a.refresh;a.expires=Date.now()+t.expires_in*1000;}return a.token;}
async function api(role,endpoint,method='GET',body){validateMutation({role,accountId:accounts.get(role)?.id,mainId:ids.main,endpoint,method,body,visibilityAccepted});
if(method==='POST'&&endpoint!=='me/playlists'){const targetId=endpoint.split('/')[1],j=read('transfer-journal.json');if(j?.mainId!==ids.main||!Object.values(j.playlists).some(p=>p.id===targetId))throw Error('Hedef aktarım kaydında yok.');const meta=await api('main','playlists/'+targetId);if(meta.owner?.id!==ids.main)throw Error('Playlist hedef hesaba ait değil.');if(!Array.isArray(body?.uris)||body.uris.length>100)throw Error('Geçersiz parça grubu.');}const u=new URL(endpoint,'https://api.spotify.com/v1/');if(u.origin!=='https://api.spotify.com'||!u.pathname.startsWith('/v1/'))throw Error('Geçersiz Spotify adresi.');
for(let retry=0;retry<4;retry++){await wait(Math.max(0,nextRequest-Date.now()));nextRequest=Date.now()+300;const r=await fetch(u,{method,headers:{Authorization:'Bearer '+await token(role),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(25000)});const text=await r.text();let data;try{data=text?JSON.parse(text):{};}catch{data={};}if(r.ok)return data;if(r.status===429){const delay=retryDelay(r,data)/1000;setStatus('Spotify istek sınırı: kısa süre sonra devam edilecek.');await wait(Math.max(1,delay)*1000);continue;}let e=Error('Spotify API '+r.status+' ('+u.pathname+')'+(r.status===403?' — hesap izinleri veya API erişim sınırı.':''));e.status=r.status;throw e;}throw Error('Spotify istek sınırı devam ediyor.');}
function engine(){const file=path.join(__dirname,'transfer.cjs');delete require.cache[require.resolve(file)];return require(file);}
const ctx={api,accounts,setStatus,write,read,mainId:ids.main};
async function migrate(){if(busy)return;for(const r of Object.keys(ids))if(!accounts.has(r)||!snapshots.has(r))return;busy=true;status.phase='transferring';setStatus('Kaynak kopyaları hazır; MAIN aktarımı başlıyor.');try{let mod=engine(),plan=mod.buildPlan(Object.keys(ids).filter(r=>r!=='main').map(r=>snapshots.get(r)));const report=await mod.transfer(ctx,plan);status.phase=report.complete?'complete':'review';setStatus(report.complete?'Aktarım tamamlandı ve MAIN üzerinde doğrulandı.':'Aktarım bitti; raporda kontrol gerektiren eksikler var.');}catch(e){status.phase='error';setStatus('Aktarım durdu: '+safeError(e));}finally{busy=false;}}
function safeError(e){return e.cause?.code==='EACCES'?'Spotify bağlantısında ağ izni eksik.':e.message==='fetch failed'?'Spotify bağlantısı kesildi; yeniden deneyebiliriz.':e.message;}
function page(body){return '<!doctype html><html lang="tr"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta http-equiv="refresh" content="8"><title>Lilt • Aktarım</title><style>body{background:#11131a;color:#eee;font:18px system-ui;max-width:800px;margin:40px auto;padding:24px}a{color:#b6a3ff}section{background:#202331;padding:20px;margin:16px 0;border-radius:14px}button{padding:12px;background:#b6a3ff;border:0;border-radius:9px;font:inherit}small{color:#bbb}</style><h1>Lilt</h1>'+body+'</html>';}
function send(res,code,body){res.writeHead(code,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','Referrer-Policy':'no-referrer','Content-Security-Policy':"default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; frame-ancestors 'none'"});res.end(page(body));}
function redirect(res,url){res.writeHead(303,{Location:url,'Cache-Control':'no-store','Referrer-Policy':'no-referrer'});res.end();}
const home=BASE+'/?key='+KEY;
const server=http.createServer(async(req,res)=>{try{if(req.headers.host!==new URL(BASE).host)return send(res,403,'Geçersiz adres.');const u=new URL(req.url,BASE);if(u.pathname==='/callback'&&req.method==='GET'){let state=u.searchParams.get('state'),p=pending.get(state);pending.delete(state);if(!p||Date.now()-p.time>600000)return send(res,400,'Giriş süresi doldu. <a href="'+home+'">Yeniden dene</a>');if(u.searchParams.has('error'))return send(res,400,'Spotify izni verilmedi. <a href="'+home+'">Geri dön</a>');const r=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:CLIENT,grant_type:'authorization_code',code:u.searchParams.get('code')||'',redirect_uri:REDIRECT,code_verifier:p.verifier}),signal:AbortSignal.timeout(25000)});if(!r.ok)throw Error('Spotify giriş doğrulaması başarısız: '+r.status);const t=await r.json();if(p.role==='main'&&!['playlist-modify-private','user-library-modify','user-follow-modify','playlist-modify-public'].every(s=>(t.scope||'').split(' ').includes(s)))throw Error('MAIN aktarım izinleri verilmedi.');const meRes=await fetch('https://api.spotify.com/v1/me',{headers:{Authorization:'Bearer '+t.access_token},signal:AbortSignal.timeout(25000)});if(!meRes.ok)throw Error('Hesap kimliği okunamadı: '+meRes.status);const me=await meRes.json();if(me.id!==ids[p.role])throw Error('Yanlış hesap seçildi. Beklenen: '+labels[p.role]+'. Spotify girişinde hesabı değiştir.');snapshots.delete(p.role);accounts.set(p.role,{id:me.id,name:me.display_name,token:t.access_token,refresh:t.refresh_token,expires:Date.now()+t.expires_in*1000});status.accounts[p.role]={id:me.id,name:me.display_name,state:'reading'};write('migration-status.json',status);queue=queue.then(async()=>{try{const s=await engine().snapshot(ctx,p.role);snapshots.set(p.role,s);status.accounts[p.role]={id:s.id,name:s.name,state:'ready',playlists:s.playlists.length,liked:s.library.liked.length};setStatus(labels[p.role]+' hazır.');}catch(e){status.accounts[p.role].state='error';status.accounts[p.role].error=safeError(e);setStatus(safeError(e));}});return redirect(res,home);}
if(u.searchParams.get('key')!==KEY)return send(res,403,'Sohbetteki Lilt bağlantısını kullan.');if(u.pathname==='/status'&&req.method==='GET'){res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store'});return res.end(JSON.stringify(status));}if(u.pathname==='/resume'&&req.method==='POST'){if(req.headers.origin!==BASE)return send(res,403,'Geçersiz istek kaynağı.');if(busy)return send(res,409,'Aktarım zaten çalışıyor.');
if(!Object.keys(ids).every(r=>accounts.has(r)&&snapshots.has(r)))return send(res,409,'Önce tüm hesapları bağla.');
let form='';for await(const chunk of req){form+=chunk;if(form.length>1024)return send(res,413,'İstek çok büyük.');}
visibilityAccepted=new URLSearchParams(form).get('visibility')==='accepted';
if(!visibilityAccepted)return send(res,400,'Görünürlük uyarısını kabul et.');
write('transfer-permission.json',{mainId:ids.main,allowTemporaryPublic:true});queue=queue.then(migrate);return redirect(res,home);}if(req.method!=='GET')return send(res,405,'Geçersiz işlem.');if(u.pathname==='/login'){if(busy)return send(res,409,'Aktarım sırasında hesap değiştirilemez.');const role=u.searchParams.get('role');if(!ids[role])throw Error('Geçersiz hesap.');const state=crypto.randomBytes(24).toString('hex'),verifier=crypto.randomBytes(48).toString('base64url');pending.set(state,{role,verifier,time:Date.now()});let scope='playlist-read-private playlist-read-collaborative user-library-read user-follow-read';if(role==='main')scope+=' playlist-modify-private playlist-modify-public user-library-modify user-follow-modify';const auth=new URL('https://accounts.spotify.com/authorize');auth.search=new URLSearchParams({client_id:CLIENT,response_type:'code',redirect_uri:REDIRECT,state,code_challenge_method:'S256',code_challenge:crypto.createHash('sha256').update(verifier).digest('base64url'),scope,show_dialog:'true'}).toString();return redirect(res,auth.href);}if(u.pathname!=='/')return send(res,404,'Sayfa bulunamadı.');let cards=Object.entries(labels).map(([role,label])=>{const a=status.accounts[role];return '<section><h2>'+esc(label)+'</h2><p>'+(a?esc(a.state==='ready'?'Hazır: '+a.liked+' beğenilen, '+a.playlists+' playlist':a.error||'Kitaplık okunuyor…'):'Bağlantı bekleniyor.')+'</p>'+(!busy?'<a href="/login?key='+KEY+'&role='+role+'">'+(a?'Yeniden bağla':'Hesaba giriş yap')+'</a>':'')+'</section>';}).join('');send(res,200,'<p><b>'+esc(status.message)+'</b></p><p>Hesaplarını bağla, ardından aktarımı başlat. Kaynaklar yalnızca okunur. Beğenilenler MAIN’e eklenir; erişilebilir playlistler kopyalanır. Okunamayan üçüncü kişi listeleri kitaplığa kaydedilebilir.</p>'+cards+(!busy?'<form method="post" action="/resume?key='+KEY+'"><label><input type="checkbox" name="visibility" value="accepted" required> Oluşturulan playlistler herkese açık olabilir. Gerçek gizliliği Spotify uygulamasından kontrol edip ayarlayacağım.</label><p><button>Aktar / Kaldığı yerden devam et</button></p></form>':'')+'<small>Kaynak hesaplar yalnızca okunur. Giriş anahtarları yalnızca program belleğinde; içerik kopyaları bilgisayarında tutulur.</small>');}catch(e){send(res,400,'<h2>İşlem tamamlanamadı</h2><p>'+esc(safeError(e))+'</p><a href="'+home+'">Lilt’e dön</a>');}});
server.on('error',e=>{console.error('Local server error: '+e.code);process.exitCode=1;});server.listen(config.port,'127.0.0.1',()=>{write('migration-status.json',status);console.log('Lilt: '+home);});setTimeout(()=>{if(!busy)server.close(()=>process.exit(0));},8*60*60*1000);
