const fs=require('node:fs'),path=require('node:path');

const types={liked:['me/tracks?limit=50','track'],albums:['me/albums?limit=50','album'],episodes:['me/episodes?limit=50','episode'],shows:['me/shows?limit=50','show'],audiobooks:['me/audiobooks?limit=50',null],artists:['me/following?type=artist&limit=50',null]};
const unique=a=>[...new Set(a)];
function uris(items,field){return items.map(i=>(field?i[field]:i)?.uri).filter(u=>/^spotify:(track|album|episode|show|audiobook|artist):[A-Za-z0-9]+$/.test(u||''));}
function prefix(actual,expected){return actual.length<=expected.length&&actual.every((u,i)=>u===expected[i]);}
async function all(api,role,endpoint){let out=[],total=null;while(endpoint){const r=await api(role,endpoint);const p=r.artists||r;if(!Array.isArray(p.items))throw Error('Spotify yanıtında liste eksik.');out.push(...p.items);total=p.total??total;endpoint=p.next;}if(total!==null&&out.length!==total)throw Error('Liste okunurken içerik sayısı değişti; yeniden denemek gerekiyor.');return out;}
async function snapshot(ctx,role){const {api,accounts,setStatus,write}=ctx;const me=accounts.get(role);setStatus(role+' kitaplığı okunuyor');let s={id:me.id,name:me.name,time:new Date().toISOString(),library:{},errors:{},playlists:[]};
for(const [kind,[ep,field]]of Object.entries(types)){try{let rows=await all(api,role,ep);s.library[kind]=uris(rows,field);if(s.library[kind].length!==rows.length)s.errors[kind+'_unavailable']=rows.length-s.library[kind].length;}catch(e){if(e.code==='QUOTA_EXCEEDED')throw e;s.errors[kind]=e.message;if(kind==='liked')throw e;}}
const ps=await all(api,role,'me/playlists?limit=50');for(const p of ps){setStatus(role+': '+p.name);const meta={id:p.id,name:p.name,owner:p.owner?.id,public:p.public,description:p.description||'',total:(p.items||p.tracks)?.total||0,snapshot:p.snapshot_id};
try{let rows=await all(api,role,'playlists/'+p.id+'/items?limit=50&additional_types=track,episode');const after=await api(role,'playlists/'+p.id);if(meta.snapshot&&after.snapshot_id!==meta.snapshot)throw Error('Playlist okuma sırasında değişti.');meta.uris=rows.map(i=>i.item||i.track).filter(i=>i&&!i.is_local&&/^spotify:(track|episode):[A-Za-z0-9]+$/.test(i.uri||'')).map(i=>i.uri);meta.unavailable=rows.length-meta.uris.length;}catch(e){if(e.code==='QUOTA_EXCEEDED')throw e;meta.error=e.message;if(meta.owner===s.id)throw Error('Kaynak playlist okunamadı: '+meta.name+' — '+e.message);}
s.playlists.push(meta);}
write('snapshot-'+role+'.json',s);return s;}
function buildPlan(sources){const library={};for(const kind of Object.keys(types))library[kind]=unique(sources.flatMap(s=>s.library[kind]||[]));const playlists=[],followed=new Map(),issues=[];for(const s of sources){for(const [kind,error]of Object.entries(s.errors))issues.push({account:s.name,kind,error});for(const p of s.playlists){if(Array.isArray(p.uris)){playlists.push({...p,sourceId:s.id,sourceName:s.name,key:'lilt:'+s.id+':'+p.id});if(p.unavailable)issues.push({account:s.name,playlist:p.name,unavailable:p.unavailable});}else if(p.owner!==s.id&&p.public===true){followed.set(p.id,p);issues.push({account:s.name,playlist:p.name,action:'Follow original playlist; API content read unavailable',error:p.error});}else issues.push({account:s.name,playlist:p.name,error:p.error});}}return {library,playlists,followed:[...followed.values()],issues};}
async function transfer(ctx,plan){const {accounts,write,read,setStatus,api}=ctx;const MAIN=ctx.mainId;if(!MAIN)throw Error('Target account is not configured.');if(accounts.get('main')?.id!==MAIN)throw Error('MAIN kimliği uyuşmuyor.');const journal=read('transfer-journal.json')||{mainId:MAIN,playlists:{}};if(journal.mainId!==MAIN)throw Error('Aktarım kaydı başka MAIN hesabına ait.');const uiPrivacy=read('privacy-ui-verified.json')||{playlists:{}};const permission=read('transfer-permission.json');const allowTemporaryPublic=permission?.mainId===MAIN&&permission.allowTemporaryPublic===true;const report={mainId:MAIN,started:new Date().toISOString(),playlists:[],library:{},followed:[],issues:[...plan.issues]};write('transfer-plan.json',plan);let targetLists=await all(api,'main','me/playlists?limit=50');
for(const [kind,[endpoint,field]]of Object.entries(types)){let desired=plan.library[kind];if(!desired.length)continue;setStatus('MAIN kitaplığı: '+kind);try{let before=uris(await all(api,'main',endpoint),field),present=new Set(before),missing=desired.filter(u=>!present.has(u));for(let i=0;i<missing.length;i+=40)await api('main','me/library?uris='+encodeURIComponent(missing.slice(i,i+40).join(',')),'PUT');let after=uris(await all(api,'main',endpoint),field),now=new Set(after);let absent=desired.filter(u=>!now.has(u)),lost=before.filter(u=>!now.has(u));report.library[kind]={sourceUnique:desired.length,alreadyPresent:desired.length-missing.length,added:missing.length-absent.length,total:now.size,missing:absent,previousItemsMissing:lost,verified:!absent.length&&!lost.length};}catch(e){if(e.code==='QUOTA_EXCEEDED')throw e;report.library[kind]={error:e.message,verified:false};}write('transfer-report.json',report);}
for(const p of plan.playlists){setStatus('MAIN playlist: '+p.name);let id=journal.playlists[p.key]?.id;let matches=targetLists.filter(q=>q.owner?.id===MAIN&&(q.description||'').includes('['+p.key+']'));if(!id&&matches.length>1)throw Error('Birden fazla aktarım kopyası bulundu: '+p.name);if(!id&&matches.length)id=matches[0].id;if(!id){if(!allowTemporaryPublic)throw Error('Playlist oluşturmak için görünürlük uyarısını kabul et.');const created=await api('main','me/playlists','POST',{name:p.name,description:(p.description||'').slice(0,210)+' ['+p.key+']'});id=created.id;if(!id)throw Error('Yeni playlist kimliği alınamadı');journal.playlists[p.key]={id};write('transfer-journal.json',journal);targetLists.push(created);}
let meta=await api('main','playlists/'+id); write('target-metadata-debug.json',{id:meta.id,owner:meta.owner,public:meta.public,description:meta.description,name:meta.name,expectedKey:p.key});if(meta.owner?.id!==MAIN||(!allowTemporaryPublic&&meta.public!==false&&!(uiPrivacy.mainId===MAIN&&uiPrivacy.playlists[id]?.key===p.key))||!(meta.description||'').includes('['+p.key+']'))throw Error('Hedef playlist kimliği veya gizliliği uyuşmuyor: '+p.name);if(p.uris.length&&!allowTemporaryPublic&&!(uiPrivacy.mainId===MAIN&&uiPrivacy.playlists[id]?.key===p.key))throw Error('Spotify arayüzünden gizlilik doğrulaması bekleniyor: '+p.name);let actual=(await all(api,'main','playlists/'+id+'/items?limit=50&additional_types=track,episode')).map(i=>(i.item||i.track)?.uri);if(!prefix(actual,p.uris))throw Error('Hedef playlist içeriği değişmiş: '+p.name);while(actual.length<p.uris.length){const previousLength=actual.length;await api('main','playlists/'+id+'/items','POST',{uris:p.uris.slice(actual.length,actual.length+100)});actual=(await all(api,'main','playlists/'+id+'/items?limit=50&additional_types=track,episode')).map(i=>(i.item||i.track)?.uri);if(actual.length<=previousLength)throw Error('Spotify parça eklemesini henüz doğrulamadı: '+p.name);if(!prefix(actual,p.uris))throw Error('Parça sırası doğrulanamadı: '+p.name);journal.playlists[p.key]={id,verifiedCount:actual.length};write('transfer-journal.json',journal);}
report.playlists.push({sourceId:p.sourceId,sourcePlaylist:p.id,name:p.name,targetId:id,count:actual.length,private:uiPrivacy.mainId===MAIN&&uiPrivacy.playlists[id]?.key===p.key?true:null,apiPublic:meta.public,privacyNeedsManual:!(uiPrivacy.mainId===MAIN&&uiPrivacy.playlists[id]?.key===p.key),url:'https://open.spotify.com/playlist/'+id,verified:true});write('transfer-report.json',report);}
for(const p of plan.followed){setStatus('MAIN takip edilen liste: '+p.name);try{await api('main','me/library?uris='+encodeURIComponent('spotify:playlist:'+p.id),'PUT');report.followed.push({id:p.id,name:p.name,saved:true});}catch(e){if(e.code==='QUOTA_EXCEEDED')throw e;report.followed.push({id:p.id,name:p.name,error:e.message});}}
if(report.followed.length){const lists=await all(api,'main','me/playlists?limit=50'),ids=new Set(lists.map(p=>p.id));for(const p of report.followed)p.verified=ids.has(p.id);}
report.finished=new Date().toISOString();report.complete=report.playlists.every(p=>p.verified)&&Object.values(report.library).every(k=>k.verified)&&report.followed.every(p=>p.verified)&&!report.issues.some(i=>i.unavailable||(!i.action&&i.error));write('transfer-report.json',report);return report;}
module.exports={snapshot,buildPlan,transfer,all,prefix,unique,uris,types};
